# Generated by Django 2.1.7 on 2019-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190402_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='module_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=20),
        ),
    ]
