# Generated by Django 2.1.7 on 2019-04-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190402_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
    ]
