# Generated by Django 2.1.7 on 2019-04-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_quiz_is_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='have_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('image', 'image'), ('text', 'text')], default='text', max_length=20),
        ),
    ]
