# Generated by Django 2.1.7 on 2019-03-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compID', models.IntegerField()),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('created_by', models.IntegerField()),
                ('contains_modules', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnerID', models.IntegerField()),
                ('learnerName', models.CharField(max_length=200)),
                ('takecourse', models.IntegerField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.IntegerField()),
                ('moduleTitle', models.CharField(max_length=200)),
                ('containsComp', models.IntegerField()),
                ('containsQuiz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.IntegerField()),
                ('questionID', models.IntegerField()),
            ],
        ),
    ]
