# Generated by Django 2.1.7 on 2019-04-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='pass_date',
        ),
    ]
