# Generated by Django 2.1.7 on 2019-04-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modulet_question_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulet',
            name='counter',
        ),
    ]
