# Generated by Django 2.1.7 on 2019-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_learner_pass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='pass_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
