# Generated by Django 2.1.7 on 2019-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_modulet_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulet',
            name='title',
            field=models.CharField(default='unnamed', max_length=200),
        ),
    ]
