# Generated by Django 2.1.7 on 2019-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_modulet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='componentType',
            field=models.IntegerField(default='1'),
        ),
    ]
