# Generated by Django 2.1.7 on 2019-04-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question'),
        ('main', '0005_staff_token'),
    ]

    operations = [
    ]
