# Generated by Django 2.2 on 2019-04-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_staff_token'),
        ('main', '0007_question'),
    ]

    operations = [
    ]
