# Generated by Django 2.2 on 2019-04-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question'),
        ('main', '0005_staff_token'),
    ]

    operations = [
    ]
