# Generated by Django 2.1.7 on 2019-04-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_category_contain_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='used',
            field=models.IntegerField(default='0'),
        ),
    ]
