# Generated by Django 2.1.7 on 2019-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190426_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='numOfQuestion',
            field=models.IntegerField(default=0),
        ),
    ]
