# Generated by Django 2.1.7 on 2019-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_courset_autobio'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
