# Generated by Django 2.1.7 on 2019-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190426_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizt',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
