# Generated by Django 2.1.7 on 2019-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_quizt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorinfo',
            name='email',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
